version: '3.8'

services:
  claude-code:
    build: .
    container_name: claude-code-${ROLE}
    volumes:
      - .:/projects/${ROLE}
      - ./claude.local/shared:/home/developer/.claude
      - ./claude.local/shared/.claude.json:/home/developer/.claude.json
      - ./claude.local/${ROLE}/.bash_history:/home/developer/.bash_history
      - ~/.claude/CLAUDE.md:/home/developer/.claude/CLAUDE.md
      - ~/.claude/.credentials.json:/home/developer/.claude/.credentials.json
      - ~/.config/git:/home/developer/.config/git
      - ~/.ssh:/home/developer/.ssh:ro
      - ./claude.local/shared/.npm-global:/home/developer/.npm-global
      - ./claude.local/shared/.config/gh:/home/developer/.config/gh
    stdin_open: true
    tty: true
    working_dir: /projects/${ROLE}
    command: bash -c "/projects/${ROLE}/scripts/start-claude-code.sh; exec bash"
